apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-list-deployment
  labels:
    app: product-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-list
  template:
    metadata:
      labels:
        app: product-list
    spec:
      containers:
      - name: product-list
        imagePullPolicy: Never
        image: direnakkoc/product-list:latest
        ports:
        - containerPort: 3000